### ISSUE TITLE
Using Layouts other than the Default Layout

### ISSUE THREAD

**Issue by vahid-dan** [benbalter/jekyll-optional-front-matter#11]
Hi;

This plugin uses the default layout for creating HTML pages from MarkDown files without YAML front matter. Is there any way to make it use other layouts for a specific page or simply not to use any specific layout and just convert the MarkDown to HTML?

Thanks in advance.

Vahid

**Comment by qwtel** [comment]
I think you want to check out this: https://github.com/benbalter/jekyll-default-layout

**Comment by ketozhang** [comment]
While that's nice why not add a configuration in `config.yml` that let `jekyll-optional-front-matter` decide which layout to use for YAML-less files?

**Comment by qwtel** [comment]
you should be able to achieve this with Jekyll front matter defaults. no plugin necessary.

```yml
defaults:
  - scope:
      path: '' # see Jekyll docs for more scope options
    values:
      layout: <your choice>

**Comment by ketozhang** [comment]
Yes it's in the Jekyll documentation but I also require optional front matter because I have hundreds of markdown document without front matter.

However you are right `jekyll-optional-front-matter` works with scope as well.
