### ISSUE TITLE
Missing Gem Install Instruction in README

### ISSUE THREAD

**Issue by ketozhang** [benbalter/jekyll-optional-front-matter#12]
I'm not very familiar with how Gem works but so far from the Jekyll website there is one instruction missing on the README.

## Usage

1. Add the following to your site's Gemfile:

  ```ruby
  gem 'jekyll-optional-front-matter'
  ```

2. Install with Gem

```bash
$ gem install jekyll-optional-front-matter # May need sudo
$ bundler install jekyll-optional-front-matter #I wasn't able to get this one working
```

3. Add the following to your site's config file:

  ```yml
  gems:
    - jekyll-optional-front-matter
  ```

Without step 2, Jekyll fails to recognized that jekyll-optional-front-matter has been installed. Am I suppose to run a dependency check on jekyll like `gem update jekyll`?

**Nevermind it's ``bundle install``**. Either way this is confusing for new users

**Comment by benbalter** [comment]
@ketozhang Would you be able to submit a pull request to update the documentation?
