### ISSUE TITLE
Feature Request: Support SASS files

### ISSUE THREAD

**Issue by SLaks** [benbalter/jekyll-optional-front-matter#14]
I'd love to be able to use this plugin to make Jekyll [compile all SASS files](https://jekyllrb.com/docs/assets/) in my site without adding front matter (which breaks my editor).

But that doesn't seem to work.

Can you please add that?

**Comment by qwtel** [comment]
I think what you actually want is sass imports, i.e. 

```scss
---
# assets/css/style.scss
# This is the only file that needs a front matter
---
@import('all-my-styles')
```

Then in your "sass dir (defaults to `_sass` I think), add `all-my-styles.scss` or `_all-my-styles.scss` (both should be valid) and add your styles here. No front matter required (in fact, not allowed)

**Comment by SLaks** [comment]
That's what I'm doing, but it's annoying (especially with many entry-point SASS files)

**Comment by kenman345** [comment]
Not sure if I'm 100% correct but I am not sure if this plugin really can do anything like that. Seeing as its taking static files and making Jekyll consider them as pages, its a bit different than taking something Jekyll is ignoring as a static file.
