### ISSUE TITLE
Is there a remove_originals setting for the non-optional front-matter?

### ISSUE THREAD

**Issue by samuelgoto** [benbalter/jekyll-optional-front-matter#16]
The remove_original flag works great for me when front-matter is optional in this plugin.

```
optional_front_matter:
  remove_originals: true
```

Any chance you'd know if there is such a setting for when front-matter is passed (probably outside of the scope of this plugin, but wanted to check in case you knew)?

**Comment by kenman345** [comment]
I think I understand what you're asking. If you mean that frontmatter exists on the original files, then you simply would include them in the `_config.yml` file under `exclude:`

This does mean that they wouldnt be copied over to the rendered site as .md's though. It would just not copy them over at all.
