### ISSUE TITLE
jekyll-optional-front-matter no longer works now that jekyll 4.0 has been released

### ISSUE THREAD

**Issue by gene1wood** [benbalter/jekyll-optional-front-matter#21]
### Describe the bug

With the release of jekyll 4.0, `jekyll-optional-front-matter` won't install because of the version constraints.

### Steps to reproduce the behavior

1. Follow the [usage instructions](https://github.com/benbalter/jekyll-optional-front-matter#usage) to add `jekyll-optional-front-matter` to your `Gemfile
2. Install the Gem

### Expected behavior

Installation and use of the plugin would work in the current version of Jekyll

### Actual behavior

```
$ bundle update
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (~> 4.0.0)

    jekyll-optional-front-matter was resolved to 0.3.0, which depends on
      jekyll (~> 3.0)
```

This is likely fixed with #20

**Comment by kylekirkby** [comment]
Hi @benbalter,

I promise I'll stop pestering you sooner rather than later! Could you push a release based on the master branch for this Jekyll plugin?

:100: for helping us Jekyllers out 

BR,

Kyle
