### ISSUE TITLE
Should we remove the original markdown file?

### ISSUE THREAD

**Issue by benbalter** [benbalter/jekyll-optional-front-matter#3]
Right now, if I have `foo.md`, it'll be published as `foo.md` (a static file) **and** `foo.html` (a Page) in the resulting site.

I think that's the best behavior, since that would remain backwards compatible for users that would want the raw markdown for whatever reason.

@parkr, @jldec Thoughts?

**Comment by parkr** [comment]
Yeah! Kind of cool, actually. 😄

**Comment by benbalter** [comment]
(feel free to continue to comment, glad to reopen, but sounds like it makes sense to keep backward compatibility (practicality), even if not philosophically pure).

**Comment by agude** [comment]
Since you say "Feel free to comments":

I had some raw markdown files I was serving from my Github Pages site when this plugin went live. Although it made me reconsider the use of these raw files (and I'll probably move them to rendered pages), I appreciate that it didn't break the links!

**Comment by vossad01** [comment]
It appears this conversation was continued in #4
