### ISSUE TITLE
Markdown source should not be in _site

### ISSUE THREAD

**Issue by FokkeZB** [benbalter/jekyll-optional-front-matter#4]
After adding this plugin I noticed that the markdown source was also still in `_site/foo.md`, right there with `_site/foo.html`. I'd expect only to find the HTML version.

**Comment by benbalter** [comment]
@FokkeZB can you explain a bit more about what you did, what you'd expect, and what happened? Since this plugin only uses Jekyll's native `static_files`, `_site/*` should be excluded by default.

**Comment by FokkeZB** [comment]
What I mean is that for Markdown files that include front matter, you'll only find the generated HTML file in `_site`. With this plugin you'll find both the `.html` and original `.md` there.

**Comment by benbalter** [comment]
Gotcha. Good catch. That was partially a purposeful design decision, in case you wanted the raw `.md` output (to make it a non-breaking change when activated by default on GitHub Pages). 

is there a reason you wouldn't want the raw markdown outputted, other that cleanliness?

**Comment by FokkeZB** [comment]
No, just cleanliness and consistency

**Comment by willnorris** [comment]
+1 for not wanting source files in the output directory.  Jekyll doesn't put the source files in the output directory normally, so I'm not sure why this plugin should.

**Comment by benbalter** [comment]
>  so I'm not sure why this plugin should.

If I had a `foo.md` file with no front matter before (published as raw markdown), and then activate this plugin, I would have a `foo.html` file, as expected, but I'd also still have the `foo.md` file, to avoid breaking the existing site. An example would be the [contributor coventant site](http://contributor-covenant.org/version/1/4/code_of_conduct.md). If we removed the original file, there'd be no way to publish raw Markdown (for tutorials, client-side rendering, etc.).

**Comment by FokkeZB** [comment]
@benbalter good point, but of course enabling this plugin is conscious choice. If we'd allow people to add to the [blacklist](https://github.com/benbalter/jekyll-optional-front-matter/blob/master/lib/jekyll-optional-front-matter.rb#L8) then they could still enable the plugin and excluded any files they'd like to ignore. This would have the additional benefit that it wouldn't generate the unwanted `.html` file either.

**Comment by benbalter** [comment]
> but of course enabling this plugin is conscious choice.

On GitHub Pages, it's activated by default (to mirror the experience of publishing Markdown files elsewhere on GitHub).

> This would have the additional benefit that it wouldn't generate the unwanted .html file either.

For me, it comes down to potential harm. If I had a file that was being published, and all of a sudden it's not published, that could break my site. If all of a sudden another file is published (that's not linked anywhere), it feels less philosophically pure, to be sure, but it's pragmatic (unless I'm missing the downside of publishing the extra file).

**Comment by FokkeZB** [comment]
> On GitHub Pages, it's activated by default

OK, so then indeed it should leave `.md` there by default. So perhaps add an option to **not** do that?

**Comment by benbalter** [comment]
> So perhaps add an option to not do that?

👍 Glad to help review a pull request if anyone's interested in working on this.

**Comment by willnorris** [comment]
+1 that I now understand why the current behavior is the correct default.  (The contributor covenant site helps make that clear).  I'll try working on a PR to add an option.

**Comment by benbalter** [comment]
Fixed by #9.
