### ISSUE TITLE
Plugin does not work for markdown sources in collections

### ISSUE THREAD

**Issue by FokkeZB** [benbalter/jekyll-optional-front-matter#5]
Markdown files with no front matter are copied to `_site` as-is, with no `.html` version.

I'd expect the plugin to work on markdown sources in collections as well.

**Comment by benbalter** [comment]
@FokkeZB are you saying that without the plugin they're converted to markdown, or that they're not copied at all? With the plugin, it sounds like they're copied but not rendered, is that correct?

**Comment by FokkeZB** [comment]
What I mean is that Markdown files with no front matter that are part of collections are not processed by this plugin. As the source code shows [it only processed pages](https://github.com/benbalter/jekyll-optional-front-matter/blob/master/lib/jekyll-optional-front-matter/generator.rb#L15).

**Comment by mcdemarco** [comment]
This would be especially helpful because Jekyll itself used to process files without frontmatter in collections, but stopped doing so in version 2.2.0.   https://github.com/jekyll/jekyll-help/issues/223

**Comment by benbalter** [comment]
I'd be glad to a review a PR if someone would like to make this *opt-in* for collections (e.g., via flag when the collection is describe in the config).

**Comment by kylekirkby** [comment]
Would be great to get this functionality added :) Looking to get the [96boards.org](https://www.96boards.org) documentation into a pure markdown format!

BR,

Kyle
