### ISSUE TITLE
Strip Markdown markup from title

### ISSUE THREAD

**Issue by dato** [benbalter/jekyll-optional-front-matter#6]
Headers in Markdown may include markup:

```
# My _title_ with footnote[^src]

[^src]: This article is based on previous work by J.E.D.
```

It would be nice to strip that from the title as it goes to the front-matter, since it will be treated verbatim by browsers and scripts.

Many thanks for considering,

-d

**Comment by benbalter** [comment]
I agree that that is not the intended behavior, though do not know that footnote in H1s are that common, and thus may not be able to personally tackle this in the near future. Very glad to review a PR if you or anyone else is interested.

**Comment by dato** [comment]
Eeh, this issue should have gone to benbalter/jekyll-titles-from-headings, sorry. Moved to benbalter/jekyll-titles-from-headings#15.
